addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.4.15")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"                  % "0.5.0")
addSbtPlugin("io.spray"           % "sbt-revolver"                  % "0.10.0")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"           % "1.9.16")
