name: Fly Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [temurin@17]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Setup Java (temurin@17)
        id: setup-java-temurin-17
        if: matrix.java == 'temurin@17'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Publish Local Docker Image
        run: sbt server/Docker/publishLocal
      
      - name: Fly deploy
        run: flyctl deploy --vm-cpu-kind "shared" --vm-cpus "1" --local-only --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}